/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_tecnightsenai;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lahra
 */
public class tela_novo_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form tela_novo_cadastro
     */
    public tela_novo_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_tipo_cadastro_novo_fun = new javax.swing.JComboBox<>();
        tx_nome_novo_fun = new javax.swing.JTextField();
        tx_email_novo_fun = new javax.swing.JTextField();
        tx_senha_novo_fun = new javax.swing.JTextField();
        btn_save_novo_fun = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cb_unidade_cras_novo_fun = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de cadastro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nome completo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Cpf:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Senha provisoria:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, -1, -1));

        cb_tipo_cadastro_novo_fun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionário" }));
        getContentPane().add(cb_tipo_cadastro_novo_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 320, 34));
        getContentPane().add(tx_nome_novo_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 320, 33));
        getContentPane().add(tx_email_novo_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 310, 33));
        getContentPane().add(tx_senha_novo_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 310, 33));

        btn_save_novo_fun.setBackground(new java.awt.Color(103, 178, 106));
        btn_save_novo_fun.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_save_novo_fun.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_novo_fun.setText("Cadastrar");
        btn_save_novo_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_novo_funActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save_novo_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Novo funcionário");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        cb_unidade_cras_novo_fun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRAS Ilha da Figueira", "CRAS  João Pessoa", "CRAS Centro", "CRAS Ribeirão Cavalo", "CRAS  Jaraguá 84", "CRAS Vila Lenzi", "CRAS Santo Antônio", " " }));
        cb_unidade_cras_novo_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_unidade_cras_novo_funActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Unidade CRAS:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(647, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cb_unidade_cras_novo_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_unidade_cras_novo_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 1060, 530));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Users\\lnunes\\Desktop\\pasta_nova\\TecNight_SistemaCadastro_PCD\\Projeto_TecNightSenai\\src\\main\\java\\icones\\bacgorund_novo_user.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 1850, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_novo_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_novo_funActionPerformed
     
        
        
        
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost/projeto_AcessaMais";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario,senha);
            
           
            String sql = "INSERT INTO cadastro_civil(unidade_cras, tipo_cadastro,nome_cadastro) VALUES(?,?)";
            statement = conexao.prepareStatement(sql);
            
            
            String ComboBox_TipoCad = (String) cb_tipo_cadastro_novo_fun.getSelectedItem();
            String ComboBox_UniCras = (String) cb_unidade_cras_novo_fun.getSelectedItem();
            
            
            
            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            tela_novo_cadastro.this.dispose();
            tela_login objeto2 = new   tela_login();
            objeto2.setVisible(true);
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(tela_novo_cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_save_novo_funActionPerformed

    private void cb_unidade_cras_novo_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_unidade_cras_novo_funActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_unidade_cras_novo_funActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_novo_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_novo_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_novo_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_novo_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_novo_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save_novo_fun;
    private javax.swing.JComboBox<String> cb_tipo_cadastro_novo_fun;
    private javax.swing.JComboBox<String> cb_unidade_cras_novo_fun;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tx_email_novo_fun;
    private javax.swing.JTextField tx_nome_novo_fun;
    private javax.swing.JTextField tx_senha_novo_fun;
    // End of variables declaration//GEN-END:variables
}
