/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_tecnightsenai;

import static com.mycompany.projeto_tecnightsenai.tela_consulta_daddos.cpfEdit;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lnunes
 */
public class tela_edicao_cadastro_civil extends javax.swing.JFrame {

    
    /**
     * Creates new form atividade_01_19
     */
   // public CpfRecebe  cpfEdit;
    public tela_edicao_cadastro_civil() {
        initComponents();
        PreencherCampo();
        
    }
    
    
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost/projeto_AcessaMais";
            String usuario = "root";
            String senha = "";
            
            
        private void carregarFoto(){
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecione o arquivo!");
        jfc.setFileFilter(new FileNameExtensionFilter("Arquivo de imagens (*.PNG, *.JPG, *.JPEG)", "png", "jpg", "jpeg"));
     int resultado = jfc.showOpenDialog(this);
     
     if(resultado == JFileChooser.APPROVE_OPTION){
         try{
             fis = new FileInputStream(jfc.getSelectedFile());
             tamanho = (int) jfc.getSelectedFile().length();
             Image foto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(lbl_foto_edit.getWidth(),lbl_foto_edit.getHeight(), Image.SCALE_SMOOTH);
             lbl_foto_edit.setIcon(new ImageIcon(foto));
             
         }catch(Exception e){
             System.out.print(e);
         }
     }
    }
    public String formatoData(String data) {
        String dateStr = data;//Data no formato DD/MM/YYYY
        DateTimeFormatter formatterInput = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter formatterOutput = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = LocalDate.parse(dateStr, formatterInput); // Converte a string para LocalDate
        String formattedDate = date.format(formatterOutput); // Formata a data para o novo formato
        return formattedDate;// retorno -> YYYY/MM/DD
    }
    

    
    private PreparedStatement pst;
    //fluxo de imagens
    private FileInputStream fis;
  
    //variavel do tamanho da imagem em bytes
    private int tamanho;
    
    
    //abrir explorador de arqiuvos
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_relatorio = new javax.swing.JTextField();
        btn_4 = new javax.swing.JButton();
        panel_cadastro = new javax.swing.JTabbedPane();
        panel_identificacao = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        label_cpf = new javax.swing.JLabel();
        label_data_nasc = new javax.swing.JLabel();
        label_numero_civil = new javax.swing.JLabel();
        label_cpf_tutor = new javax.swing.JLabel();
        radio_s_def = new javax.swing.JRadioButton();
        label_status = new javax.swing.JLabel();
        label_sexo = new javax.swing.JLabel();
        label_deficiencia = new javax.swing.JLabel();
        label_sobrenome = new javax.swing.JLabel();
        label_nome_tutor = new javax.swing.JLabel();
        radio_vida_status = new javax.swing.JRadioButton();
        radio_obito_status = new javax.swing.JRadioButton();
        radio_fem = new javax.swing.JRadioButton();
        radio_masc = new javax.swing.JRadioButton();
        radio_n_b = new javax.swing.JRadioButton();
        radio_n_def = new javax.swing.JRadioButton();
        tx_nome_civil_edit = new javax.swing.JTextField();
        txt_sobrenome_civil_edit = new javax.swing.JTextField();
        tx_nome_tutor_edit = new javax.swing.JTextField();
        txt_nmr_civil_edit = new javax.swing.JFormattedTextField();
        tx_cpf_civil_edit = new javax.swing.JFormattedTextField();
        txt_cpf_tutor_edit = new javax.swing.JFormattedTextField();
        txt_data_nasc_edit = new javax.swing.JFormattedTextField();
        panel_pcd = new javax.swing.JPanel();
        label_tipo_de_def = new javax.swing.JLabel();
        cb_tipo_def_edit = new javax.swing.JComboBox<>();
        label_nome_def = new javax.swing.JLabel();
        cb_nome_def_edit = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        radio_cuidador = new javax.swing.JRadioButton();
        radio_nao_cuidador = new javax.swing.JRadioButton();
        label_nivel_autonomia = new javax.swing.JLabel();
        radio_nivel_aut = new javax.swing.JRadioButton();
        radio_nivel_pouca = new javax.swing.JRadioButton();
        radio_nivel_nenhuma = new javax.swing.JRadioButton();
        label_laudo_foto = new javax.swing.JLabel();
        tempo_def = new javax.swing.JFormattedTextField();
        btn_select_img = new javax.swing.JButton();
        lbl_foto_edit = new javax.swing.JLabel();
        panel_endereco = new javax.swing.JPanel();
        label_mun = new javax.swing.JLabel();
        label_bairro = new javax.swing.JLabel();
        label_tipo_residencia = new javax.swing.JLabel();
        label_cep = new javax.swing.JLabel();
        label_rua = new javax.swing.JLabel();
        label_localidade = new javax.swing.JLabel();
        cb_municipio = new javax.swing.JComboBox<>();
        cb_tipo_residencia = new javax.swing.JComboBox<>();
        cb_bairro = new javax.swing.JComboBox<>();
        tx_rua = new javax.swing.JTextField();
        radio_urbano = new javax.swing.JRadioButton();
        radio_rural = new javax.swing.JRadioButton();
        label_numero = new javax.swing.JLabel();
        tx_numero_casa = new javax.swing.JTextField();
        txt_cep_civil = new javax.swing.JFormattedTextField();
        panel_estrutura = new javax.swing.JPanel();
        label_condicoes = new javax.swing.JLabel();
        label_locomocao = new javax.swing.JLabel();
        radio_s_locomoçao = new javax.swing.JRadioButton();
        radio_n_locomoçao = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        radio_s_acessibilidade = new javax.swing.JRadioButton();
        radio_n_acessibilidade = new javax.swing.JRadioButton();
        label_isaude = new javax.swing.JLabel();
        radio_s_isaude = new javax.swing.JRadioButton();
        radio_n_isaude = new javax.swing.JRadioButton();
        cb_escolaridade = new javax.swing.JComboBox<>();
        label_escolaridade = new javax.swing.JLabel();
        btn_save_estrutura = new javax.swing.JButton();
        cb_condEconomica = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        radio_s_recebe = new javax.swing.JRadioButton();
        radio_n_recebe = new javax.swing.JRadioButton();
        btn_save_relatorio = new javax.swing.JButton();
        menu_decima = new javax.swing.JPanel();
        label_cadastro = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu_lateral = new javax.swing.JPanel();
        label_prefeitura = new javax.swing.JLabel();
        label_consulta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tela_cadastro_civil = new javax.swing.JLabel();
        label_img_consulta_branco = new javax.swing.JLabel();
        label_sair = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_dashbord = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        jMenu15.setText("File");
        jMenuBar3.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar3.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar4.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar4.add(jMenu18);

        jMenuItem4.setText("jMenuItem4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btn_2.setBackground(new java.awt.Color(255, 255, 255));
        btn_2.setAutoscrolls(true);

        jLabel2.setText("Descreva a situação fisica do civil...");

        tx_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_relatorioActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(76, 175, 79));
        btn_4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("Export relatorio");
        btn_4.setToolTipText("");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        panel_cadastro.setBackground(new java.awt.Color(143, 198, 144));
        panel_cadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panel_cadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_cadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        panel_identificacao.setBackground(new java.awt.Color(217, 217, 217));
        panel_identificacao.setAutoscrolls(true);
        panel_identificacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_identificacao.setMaximumSize(new java.awt.Dimension(1200, 550));
        panel_identificacao.setPreferredSize(new java.awt.Dimension(1000, 495));
        panel_identificacao.setRequestFocusEnabled(false);

        label_nome.setText("Nome : ");

        label_cpf.setText("Cpf:");

        label_data_nasc.setText("Data de nascimento:");

        label_numero_civil.setText("Número de celular:");

        label_cpf_tutor.setText("Cpf tutor e/ou responsável:");

        radio_s_def.setText("Sim");
        radio_s_def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_s_defActionPerformed(evt);
            }
        });

        label_status.setText("Status:");

        label_sexo.setText("Sexo:");

        label_deficiencia.setText("Possui deficiência:");

        label_sobrenome.setText("Sobrenome:");

        label_nome_tutor.setText("Nome tutor e/ou responsável:");

        radio_vida_status.setText("Em vida");
        radio_vida_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_vida_statusActionPerformed(evt);
            }
        });

        radio_obito_status.setText("Em óbito");

        radio_fem.setText("Feminino");
        radio_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_femActionPerformed(evt);
            }
        });

        radio_masc.setText("Masculino");

        radio_n_b.setText("Não binário");

        radio_n_def.setText("Não");

        tx_nome_civil_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nome_civil_editActionPerformed(evt);
            }
        });

        tx_nome_tutor_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nome_tutor_editActionPerformed(evt);
            }
        });

        try {
            txt_nmr_civil_edit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tx_cpf_civil_edit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_cpf_tutor_edit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_data_nasc_edit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data_nasc_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_data_nasc_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_identificacaoLayout = new javax.swing.GroupLayout(panel_identificacao);
        panel_identificacao.setLayout(panel_identificacaoLayout);
        panel_identificacaoLayout.setHorizontalGroup(
            panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_data_nasc)
                                    .addComponent(txt_data_nasc_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nome_tutor)
                                    .addComponent(tx_nome_tutor_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_sobrenome)))
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_numero_civil, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tx_nome_civil_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(tx_cpf_civil_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(label_cpf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nmr_civil_edit))
                                .addGap(66, 66, 66)
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cpf_tutor_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_cpf_tutor)
                                    .addComponent(txt_sobrenome_civil_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(label_sexo))
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(radio_fem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_masc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_b)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identificacaoLayout.createSequentialGroup()
                        .addComponent(radio_vida_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_obito_status)
                        .addGap(77, 77, 77))
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addComponent(radio_s_def)
                                .addGap(18, 18, 18)
                                .addComponent(radio_n_def))
                            .addComponent(label_deficiencia)
                            .addComponent(label_status))
                        .addContainerGap())))
        );
        panel_identificacaoLayout.setVerticalGroup(
            panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_sobrenome)
                            .addComponent(label_nome))
                        .addGap(3, 3, 3)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_sobrenome_civil_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_nome_civil_edit))
                        .addGap(12, 12, 12)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identificacaoLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(label_data_nasc))
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                        .addComponent(label_status)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(radio_vida_status)
                                            .addComponent(radio_obito_status)))
                                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label_sexo)
                                            .addComponent(label_cpf))
                                        .addGap(5, 5, 5)
                                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(radio_fem)
                                            .addComponent(radio_masc)
                                            .addComponent(radio_n_b)
                                            .addComponent(tx_cpf_civil_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(label_nome_tutor)
                                .addGap(17, 17, 17))))
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(label_deficiencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_n_def)
                            .addComponent(radio_s_def))))
                .addGap(1, 1, 1)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tx_nome_tutor_edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txt_data_nasc_edit, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_cpf_tutor)
                    .addComponent(label_numero_civil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nmr_civil_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txt_cpf_tutor_edit))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panel_cadastro.addTab("Identificação", panel_identificacao);

        panel_pcd.setBackground(new java.awt.Color(217, 217, 217));
        panel_pcd.setToolTipText("");

        label_tipo_de_def.setText("Tipo de deficiência:");

        cb_tipo_def_edit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Mental", "Intelectual", "Sensorial", "Multiplas deficiências", "Visual", "Auditiva" }));

        label_nome_def.setText("Nome da deficiência:");

        cb_nome_def_edit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paralisia Cerebral", "Distrofia Muscular", "Amputação", "Esquizofrenia", "Transtorno Bipolar", "Surdez Profunda", "Perda Auditiva Neurossensorial", "Síndrome de Down", "Retardo Mental", "Austismo", "Glaucoma", "Cegueira", "Baixa visão" }));

        jLabel23.setText("A quanto tempo possui?");

        jLabel24.setText("Possui um cuidador?");

        radio_cuidador.setText("Sim");

        radio_nao_cuidador.setText("Não");

        label_nivel_autonomia.setText("Nivel de autonomia:");

        radio_nivel_aut.setText("Autonomia");

        radio_nivel_pouca.setText("Pouca autonomia");

        radio_nivel_nenhuma.setText("Nenhuma autonomia");

        label_laudo_foto.setText("Insira foto do laudo médico:");

        try {
            tempo_def.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_select_img.setText("Selecione a imagem");
        btn_select_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select_imgActionPerformed(evt);
            }
        });

        lbl_foto_edit.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panel_pcdLayout = new javax.swing.GroupLayout(panel_pcd);
        panel_pcd.setLayout(panel_pcdLayout);
        panel_pcdLayout.setHorizontalGroup(
            panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pcdLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nivel_autonomia)
                    .addComponent(label_nome_def)
                    .addComponent(cb_nome_def_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addComponent(radio_nivel_aut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_nivel_pouca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_nivel_nenhuma))
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addComponent(cb_tipo_def_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempo_def, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_pcdLayout.createSequentialGroup()
                                    .addComponent(radio_cuidador)
                                    .addGap(18, 18, 18)
                                    .addComponent(radio_nao_cuidador))
                                .addComponent(jLabel24))))
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addComponent(label_tipo_de_def)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel23)))
                .addGap(135, 135, 135)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_foto_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_laudo_foto)
                    .addComponent(btn_select_img))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panel_pcdLayout.setVerticalGroup(
            panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pcdLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo_de_def)
                    .addComponent(jLabel23)
                    .addComponent(label_laudo_foto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_select_img)
                    .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tempo_def, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(cb_tipo_def_edit)))
                .addGap(1, 1, 1)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(label_nome_def)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_nome_def_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_nivel_autonomia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_nivel_aut)
                            .addComponent(radio_nivel_pouca)
                            .addComponent(radio_nivel_nenhuma))
                        .addGap(203, 203, 203))
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_nao_cuidador)
                            .addComponent(radio_cuidador))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_foto_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panel_cadastro.addTab("PCD", panel_pcd);

        panel_endereco.setBackground(new java.awt.Color(217, 217, 217));

        label_mun.setText("Municipio:");

        label_bairro.setText("Bairro:");

        label_tipo_residencia.setText("Tipo de residência:");

        label_cep.setText("Cep:");

        label_rua.setText("Rua:");

        label_localidade.setText("Localidade:");

        cb_municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jaraguá do Sul" }));

        cb_tipo_residencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Kitnet", "Casa germinada" }));

        cb_bairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Água Verde", "Águas Claras", "Amizade", "Barra do Rio Cerro", "Barra do Rio Molha", "Boa Vista", "Braço do Ribeirão Cavalo", "Centenário", "Centro", "Chico de Paulo ", "Czerniewicz", "Estrada Nova", "Ilha da Figueira", "Jaraguá 84", "Jaraguá 99", "Jaraguá Esquerdo", "João Pessoa", "Nereu Ramos", "Nova Brasília", "Parque Malwee", "Rau", "Ribeirão Cavalo", "Rio Cerro I ", "Rio Cerro II ", "Rio da Luz", "Rio Molha", "Santa Luzia", "Santo Antônio", "São Luís ", "Tifa Martins ", "Tifa Monos", "Três Rios do Norte", "Três Rios do Sul", "Vieira ", "Vila Baependi", "Vila Lalau", "Vila Lenzi", "Vila Nova" }));

        radio_urbano.setText("Urbana");

        radio_rural.setText("Rural");

        label_numero.setText("Número:");

        try {
            txt_cep_civil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panel_enderecoLayout = new javax.swing.GroupLayout(panel_endereco);
        panel_endereco.setLayout(panel_enderecoLayout);
        panel_enderecoLayout.setHorizontalGroup(
            panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_enderecoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_numero)
                    .addComponent(label_mun)
                    .addComponent(label_bairro)
                    .addComponent(cb_municipio, 0, 179, Short.MAX_VALUE)
                    .addComponent(cb_bairro, 0, 179, Short.MAX_VALUE)
                    .addComponent(tx_numero_casa))
                .addGap(155, 155, 155)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_enderecoLayout.createSequentialGroup()
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_cep)
                            .addComponent(label_rua)
                            .addComponent(tx_rua, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txt_cep_civil))
                        .addGap(100, 100, 100)
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_localidade)
                            .addGroup(panel_enderecoLayout.createSequentialGroup()
                                .addComponent(radio_urbano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio_rural))))
                    .addComponent(cb_tipo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tipo_residencia))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        panel_enderecoLayout.setVerticalGroup(
            panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_enderecoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_enderecoLayout.createSequentialGroup()
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_cep)
                            .addComponent(label_localidade))
                        .addGap(1, 1, 1)
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cep_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio_urbano)
                            .addComponent(radio_rural))
                        .addGap(33, 33, 33)
                        .addComponent(label_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(panel_enderecoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_mun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(label_bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numero)
                    .addComponent(label_tipo_residencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        panel_cadastro.addTab("Endereço", panel_endereco);

        panel_estrutura.setBackground(new java.awt.Color(217, 217, 217));
        panel_estrutura.setPreferredSize(new java.awt.Dimension(1200, 400));

        label_condicoes.setText("Condições socieconômicas:");

        label_locomocao.setText("Dificuldade de locomoção dentro do municipio?");

        radio_s_locomoçao.setText("Sim");

        radio_n_locomoçao.setText("Não");

        jLabel27.setText("Encontra acessibilidade no comercio local?");

        radio_s_acessibilidade.setText("Sim");

        radio_n_acessibilidade.setText("Não");

        label_isaude.setText("Possui facil acesso a instituições de saúde?");

        radio_s_isaude.setText("Sim");

        radio_n_isaude.setText("Não");

        cb_escolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educação infatil", "Ensino Fundamental", "Ensino médio", "Ensino Superior", "Pós graduado", "Mestrado", "Não possui escolaridade" }));

        label_escolaridade.setText("Nivel de escolaridade?");

        btn_save_estrutura.setBackground(new java.awt.Color(0, 102, 0));
        btn_save_estrutura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_save_estrutura.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_estrutura.setText("Cadastrar civil");
        btn_save_estrutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_estruturaActionPerformed(evt);
            }
        });

        cb_condEconomica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desempregado", "Pensionista", "Aposentado", "Dependente", "Estudante" }));

        jLabel7.setText("Recebe auxilio/beneficio?");

        radio_s_recebe.setText("Sim");

        radio_n_recebe.setText("Não");

        javax.swing.GroupLayout panel_estruturaLayout = new javax.swing.GroupLayout(panel_estrutura);
        panel_estrutura.setLayout(panel_estruturaLayout);
        panel_estruturaLayout.setHorizontalGroup(
            panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estruturaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_condicoes)
                    .addComponent(label_locomocao)
                    .addComponent(cb_condEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_escolaridade)
                    .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_locomoçao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_locomoçao)))
                .addGap(169, 169, 169)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(label_isaude)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_acessibilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_acessibilidade))
                    .addComponent(jLabel27)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_recebe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_recebe))
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_isaude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_isaude)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_estruturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save_estrutura)
                .addGap(41, 41, 41))
        );
        panel_estruturaLayout.setVerticalGroup(
            panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estruturaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_condicoes)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_condEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_s_acessibilidade)
                    .addComponent(radio_n_acessibilidade))
                .addGap(33, 33, 33)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_locomocao, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_isaude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_s_locomoçao)
                    .addComponent(radio_n_locomoçao)
                    .addComponent(radio_s_isaude)
                    .addComponent(radio_n_isaude))
                .addGap(18, 18, 18)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_escolaridade)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_s_recebe)
                    .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radio_n_recebe)))
                .addGap(18, 18, 18)
                .addComponent(btn_save_estrutura)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_cadastro.addTab("Estrutura", panel_estrutura);

        btn_save_relatorio.setBackground(new java.awt.Color(76, 175, 79));
        btn_save_relatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_relatorio.setText("Salvar relatorio");
        btn_save_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_relatorioActionPerformed(evt);
            }
        });

        menu_decima.setBackground(new java.awt.Color(255, 255, 255));
        menu_decima.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_decima.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menu_decimaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        label_cadastro.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label_cadastro.setText("Edição cadastro de civil");
        label_cadastro.setMaximumSize(new java.awt.Dimension(200, 47));
        label_cadastro.setMinimumSize(new java.awt.Dimension(100, 16));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Olá, Fulano Silva!");

        javax.swing.GroupLayout menu_decimaLayout = new javax.swing.GroupLayout(menu_decima);
        menu_decima.setLayout(menu_decimaLayout);
        menu_decimaLayout.setHorizontalGroup(
            menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_decimaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(label_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addGroup(menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_decimaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_decimaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(105, 105, 105))))
        );
        menu_decimaLayout.setVerticalGroup(
            menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_decimaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel5))
                    .addGroup(menu_decimaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        menu_lateral.setBackground(new java.awt.Color(30, 101, 40));

        tela_cadastro_civil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tela_cadastro_civilMouseClicked(evt);
            }
        });

        label_img_consulta_branco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_img_consulta_brancoMouseClicked(evt);
            }
        });

        label_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_sairMouseClicked(evt);
            }
        });

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        label_dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dashbordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menu_lateralLayout = new javax.swing.GroupLayout(menu_lateral);
        menu_lateral.setLayout(menu_lateralLayout);
        menu_lateralLayout.setHorizontalGroup(
            menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_lateralLayout.createSequentialGroup()
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_prefeitura)
                            .addGroup(menu_lateralLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_dashbord)
                                    .addComponent(label_sair))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel18)
                                    .addComponent(label_img_consulta_branco)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(menu_lateralLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_consulta)
                                    .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(menu_lateralLayout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(49, 49, 49))
                                        .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)))))))
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tela_cadastro_civil))
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_lateralLayout.setVerticalGroup(
            menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_lateralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addComponent(label_prefeitura)
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tela_cadastro_civil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_consulta)))
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(label_img_consulta_branco)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_lateralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_dashbord)
                        .addGap(51, 51, 51)))
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel9)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_lateralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_sair)
                        .addGap(86, 86, 86)))
                .addComponent(jLabel19)
                .addGap(107, 107, 107)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(btn_save_relatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_4))
                            .addComponent(tx_relatorio)
                            .addComponent(panel_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btn_2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_decima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(menu_decima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_relatorio)
                    .addComponent(btn_4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menu_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(btn_2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_relatorioActionPerformed

        tela_edicao_cadastro_civil.this.dispose();
        tela_consulta_daddos objeto1 = new tela_consulta_daddos();
        objeto1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_relatorioActionPerformed

    private void tx_nome_tutor_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nome_tutor_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nome_tutor_editActionPerformed

    private void tx_nome_civil_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nome_civil_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nome_civil_editActionPerformed

    private void radio_s_defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_s_defActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_s_defActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed

        try {
           String desktopPath = System.getProperty("user.home") + "/Desktop/";
            File desktopDir = new File(desktopPath);
            if (!desktopDir.exists()) {
                desktopDir.mkdirs(); 
            }
            String filePath = desktopPath + "RELATORIO.txt";
            FileWriter arquivo = new FileWriter(filePath);
            PrintWriter escrever = new PrintWriter(arquivo);

            escrever.printf("Relatorio descritivo sobre civil: " + tx_relatorio.getText());

            arquivo.close();

            JOptionPane.showMessageDialog(null, "Arquivo exportado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao exportar o arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
       
        // TODO add your handling code here:
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void tx_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_relatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_relatorioActionPerformed

    private void panel_cadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_cadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_cadastroAncestorAdded

    private void menu_decimaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menu_decimaAncestorAdded



        // TODO add your handling code here:
    }//GEN-LAST:event_menu_decimaAncestorAdded

    private void radio_vida_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_vida_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_vida_statusActionPerformed

    private void tela_cadastro_civilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tela_cadastro_civilMouseClicked

        tela_edicao_cadastro_civil.this.dispose();
        tela_edicao_cadastro_civil objeto = new tela_edicao_cadastro_civil();
        objeto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tela_cadastro_civilMouseClicked

    private void label_img_consulta_brancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_img_consulta_brancoMouseClicked

        tela_edicao_cadastro_civil.this.dispose();
        tela_consulta_daddos objeto = new tela_consulta_daddos();
        objeto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_label_img_consulta_brancoMouseClicked

    private void label_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sairMouseClicked

        JOptionPane.showMessageDialog(null, "Você saiu do sistema!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_label_sairMouseClicked
 
  
    
    public void PreencherCampo(){
    
    
        try {
         
        
            conexao = DriverManager.getConnection(url, usuario, senha);
              
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/projeto_AcessaMais", "root", "");
            String sql = "SELECT * FROM cadastro_civil WHERE cpf_civil = ?";
                   

            PreparedStatement banco = con.prepareStatement(sql);
            
            banco.setString(1, cpfEdit);
            ResultSet resultado = banco.executeQuery();
            
              if (resultado.next()) {
             tx_nome_civil_edit.setText(resultado.getString("nome_civil"));
             txt_sobrenome_civil_edit.setText(resultado.getString("sobrenome_civil"));
             tx_cpf_civil_edit.setText(resultado.getString("cpf_civil"));
             txt_data_nasc_edit.setText(resultado.getString("data_nasc"));
             txt_nmr_civil_edit.setText(resultado.getString("num_cel"));
             tx_nome_tutor_edit.setText(resultado.getString("nome_tutor_civil"));
             txt_cpf_tutor_edit.setText(resultado.getString("cpf_tutor_civil"));
             Blob blob = resultado.getBlob("foto_civil");
             int blobLength = (int) blob.length();  

         
            byte[] bytes = blob.getBytes(1, blobLength);

           
            ImageIcon imageIcon = new ImageIcon(bytes);       
            lbl_foto_edit.setIcon(imageIcon);
            
            String tipo_deficiencia = resultado.getString("tipo_deficiencia");
             cb_tipo_def_edit.setSelectedItem(tipo_deficiencia);
             
            String nome_def = resultado.getString("nome_deficiencia");
            cb_nome_def_edit.setSelectedItem(nome_def);
    
  
          
          
          //  
         //   txt_data_nasc_edit.setText(resultado.getString("date_nasc"));
         //   txt_nmr_civil_edit.setText(resultado.getString("num_cel"));
         //   txt_nmr_civil_edit.setText(resultado.getString("sobrenome_civil"));
         
            // etc.
        }

        banco.close();
        con.close();
        } catch (SQLException ex) {
            Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        tela_edicao_cadastro_civil.this.dispose();
        tela_dashbord objeto2 = new tela_dashbord();
        objeto2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    
    private void CpfExiste(){
        
        try {
        
            conexao = DriverManager.getConnection(url, usuario,senha);  
            
            String sqlCheck = "SELECT cpf_civil FROM cadastro_civil WHERE cpf_civil = ?";
            statement = conexao.prepareStatement(sqlCheck);
            statement.setString(1, tx_cpf_civil_edit.getText());
            ResultSet rs = statement.executeQuery();
            
            if (rs.next()) {
               
                JOptionPane.showMessageDialog(null, "CPF já cadastrado!");
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btn_save_estruturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_estruturaActionPerformed
            
            
 
        try {
        
            
            conexao = DriverManager.getConnection(url, usuario,senha);
            
           CpfExiste();
           
           
        String sql = "INSERT INTO cadastro_civil(cpf_civil,nome_civil,sobrenome_civil,date_criacao,data_nasc,nome_tutor_civil,cpf_tutor_civil,possui_deficiencia,status_civil,sexo_civil,nivel_autonomia, tipo_deficiencia,nome_deficiencia,possui_cuidador,foto_civil, municipio_civil, bairro_civil,numero_res_civil,cep_civil, rua_civil,localidade_civil,tipo_res_civil,nivel_esc,nivel_socieconomico,possui_dificuldadeLocomocao,acesso_saude,acesso_local,recebe_aux,num_cel) VALUES(?,?,?,now(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        statement = conexao.prepareStatement(sql);
         
         
  
            String groupDef = "";
            if(radio_s_def.isSelected()) {
                groupDef+="Sim";
            } else {
                groupDef+="Não";
            }

            String groupStatus = "";
            if(radio_vida_status.isSelected()) {
                groupStatus+="Vivo";
            } else {
                groupStatus+="Em óbito";
            }

            String groupSexo = "";
            if(radio_fem.isSelected()) {
                groupSexo+="Feminino";
            } else if(radio_masc.isSelected()) {
                groupSexo+="Masculino";
            }else{
                groupSexo+="Outro";
            }
            
             String groupAutonomia = "";
            if(radio_nivel_aut.isSelected()) {
                groupAutonomia+="Autonomia";
            } else if(radio_nivel_pouca.isSelected()) {
                groupAutonomia+="Pouca";
            }else{
                groupAutonomia+="Nenhuma";
            }
            
             String groupCuidador = "";
            if(radio_cuidador.isSelected()) {
                groupCuidador+="Sim";
            } else {
                groupCuidador+="Não";
            }
            
            String groupLocalidade = "";
            if(radio_urbano.isSelected()) {
                groupLocalidade+="Urbana";
            } else {
                groupLocalidade+="Rural";
            }
            
             String groupAuxilio = "";
            if(radio_s_recebe.isSelected()) {
                groupAuxilio+="Sim";
            } else {
                groupAuxilio+="Não";
            }
            
            String groupAcessComercio = "";
            if(radio_s_acessibilidade.isSelected()) {
                groupAcessComercio+="Sim";
            } else {
                groupAcessComercio+="Não";
            }
            
               String groupAcess = "";
            if(radio_s_locomoçao.isSelected()) {
                groupAcess+="Sim";
            } else {
                groupAcess+="Não";
            }
            
              String groupAcessSaude = "";
            if(radio_s_isaude.isSelected()) {
                groupAcessSaude+="Sim";
            } else {
                groupAcessSaude+="Não";
            }
            
            
            
            String ComboBox_TipoDef = (String) cb_tipo_def_edit.getSelectedItem();
            String ComboBox_NomeDef = (String) cb_nome_def_edit.getSelectedItem();
            String ComboBox_Municipio = (String) cb_municipio.getSelectedItem();
            String ComboBox_Bairro = (String) cb_bairro.getSelectedItem();
            String ComboBox_Residencia = (String) cb_tipo_residencia.getSelectedItem();
            String ComboBox_Economica = (String) cb_condEconomica.getSelectedItem();
            String ComboBox_Escola = (String) cb_escolaridade.getSelectedItem();

            String data = txt_data_nasc_edit.getText();
            String datanascimento = formatoData(data);

            statement.setString(1, tx_cpf_civil_edit.getText());
            statement.setString(2, tx_nome_civil_edit.getText());
            statement.setString(3, txt_sobrenome_civil_edit.getText());
            statement.setString(4, datanascimento);
            statement.setString(5, tx_nome_tutor_edit.getText());
            statement.setString(6, txt_cpf_tutor_edit.getText());
            statement.setString(7, groupDef);
            statement.setString(8, groupStatus);
            statement.setString(9, groupSexo);     
            statement.setString(10, groupAutonomia);
            statement.setString(11, ComboBox_TipoDef);    
            statement.setString(12, ComboBox_NomeDef);    
            statement.setString(13, groupCuidador); 
            statement.setBlob(14, fis, tamanho);
            statement.setString(15, ComboBox_Municipio); 
            statement.setString(16, ComboBox_Bairro); 
            statement.setString(17, tx_numero_casa.getText());
            statement.setString(18, txt_cep_civil.getText());   
            statement.setString(19, tx_rua.getText());  
            statement.setString(20, groupLocalidade); 
            statement.setString(21, ComboBox_Residencia); 
            statement.setString(22, ComboBox_Escola); 
            statement.setString(23, ComboBox_Economica);    
            statement.setString(24, groupAcessComercio); 
            statement.setString(25, groupAcessSaude);   
            statement.setString(26, groupAcess); 
            statement.setString(27, groupAuxilio); 
            statement.setString(28, txt_nmr_civil_edit.getText());
            
            statement.execute();
               
             statement.close();
             JOptionPane.showMessageDialog(null, "CIVIL CADASTRADO COM SUCESSO");
             
                tela_edicao_cadastro_civil.this.dispose();
                tela_consulta_daddos objeto = new tela_consulta_daddos();
                objeto.setVisible(true);
          
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        
    }//GEN-LAST:event_btn_save_estruturaActionPerformed

    private void radio_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_femActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_femActionPerformed

    private void btn_select_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select_imgActionPerformed

          carregarFoto();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_select_imgActionPerformed

    private void txt_data_nasc_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_data_nasc_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_data_nasc_editActionPerformed

    private void label_dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashbordMouseClicked

        tela_edicao_cadastro_civil.this.dispose();
        tela_dashbord objeto2 = new tela_dashbord();
        objeto2.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_label_dashbordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_edicao_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_edicao_cadastro_civil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_2;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_save_estrutura;
    private javax.swing.JButton btn_save_relatorio;
    private javax.swing.JButton btn_select_img;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_bairro;
    private javax.swing.JComboBox<String> cb_condEconomica;
    private javax.swing.JComboBox<String> cb_escolaridade;
    private javax.swing.JComboBox<String> cb_municipio;
    private javax.swing.JComboBox<String> cb_nome_def_edit;
    private javax.swing.JComboBox<String> cb_tipo_def_edit;
    private javax.swing.JComboBox<String> cb_tipo_residencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel label_bairro;
    private javax.swing.JLabel label_cadastro;
    private javax.swing.JLabel label_cep;
    private javax.swing.JLabel label_condicoes;
    private javax.swing.JLabel label_consulta;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_cpf_tutor;
    private javax.swing.JLabel label_dashbord;
    private javax.swing.JLabel label_data_nasc;
    private javax.swing.JLabel label_deficiencia;
    private javax.swing.JLabel label_escolaridade;
    private javax.swing.JLabel label_img_consulta_branco;
    private javax.swing.JLabel label_isaude;
    private javax.swing.JLabel label_laudo_foto;
    private javax.swing.JLabel label_localidade;
    private javax.swing.JLabel label_locomocao;
    private javax.swing.JLabel label_mun;
    private javax.swing.JLabel label_nivel_autonomia;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_nome_def;
    private javax.swing.JLabel label_nome_tutor;
    private javax.swing.JLabel label_numero;
    private javax.swing.JLabel label_numero_civil;
    private javax.swing.JLabel label_prefeitura;
    private javax.swing.JLabel label_rua;
    private javax.swing.JLabel label_sair;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel label_sobrenome;
    private javax.swing.JLabel label_status;
    private javax.swing.JLabel label_tipo_de_def;
    private javax.swing.JLabel label_tipo_residencia;
    private javax.swing.JLabel lbl_foto_edit;
    private javax.swing.JPanel menu_decima;
    private javax.swing.JPanel menu_lateral;
    private javax.swing.JTabbedPane panel_cadastro;
    private javax.swing.JPanel panel_endereco;
    private javax.swing.JPanel panel_estrutura;
    private javax.swing.JPanel panel_identificacao;
    private javax.swing.JPanel panel_pcd;
    private javax.swing.JRadioButton radio_cuidador;
    private javax.swing.JRadioButton radio_fem;
    private javax.swing.JRadioButton radio_masc;
    private javax.swing.JRadioButton radio_n_acessibilidade;
    private javax.swing.JRadioButton radio_n_b;
    private javax.swing.JRadioButton radio_n_def;
    private javax.swing.JRadioButton radio_n_isaude;
    private javax.swing.JRadioButton radio_n_locomoçao;
    private javax.swing.JRadioButton radio_n_recebe;
    private javax.swing.JRadioButton radio_nao_cuidador;
    private javax.swing.JRadioButton radio_nivel_aut;
    private javax.swing.JRadioButton radio_nivel_nenhuma;
    private javax.swing.JRadioButton radio_nivel_pouca;
    private javax.swing.JRadioButton radio_obito_status;
    private javax.swing.JRadioButton radio_rural;
    private javax.swing.JRadioButton radio_s_acessibilidade;
    private javax.swing.JRadioButton radio_s_def;
    private javax.swing.JRadioButton radio_s_isaude;
    private javax.swing.JRadioButton radio_s_locomoçao;
    private javax.swing.JRadioButton radio_s_recebe;
    private javax.swing.JRadioButton radio_urbano;
    private javax.swing.JRadioButton radio_vida_status;
    private javax.swing.JLabel tela_cadastro_civil;
    private javax.swing.JFormattedTextField tempo_def;
    private javax.swing.JFormattedTextField tx_cpf_civil_edit;
    private javax.swing.JTextField tx_nome_civil_edit;
    private javax.swing.JTextField tx_nome_tutor_edit;
    private javax.swing.JTextField tx_numero_casa;
    private javax.swing.JTextField tx_relatorio;
    private javax.swing.JTextField tx_rua;
    private javax.swing.JFormattedTextField txt_cep_civil;
    private javax.swing.JFormattedTextField txt_cpf_tutor_edit;
    private javax.swing.JFormattedTextField txt_data_nasc_edit;
    private javax.swing.JFormattedTextField txt_nmr_civil_edit;
    private javax.swing.JTextField txt_sobrenome_civil_edit;
    // End of variables declaration//GEN-END:variables
}
