/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_tecnightsenai;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author lnunes
 */
public class tela_cadastro_civil extends javax.swing.JFrame {

    /**
     * Creates new form atividade_01_19
     */
    public tela_cadastro_civil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        btn_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_relatorio = new javax.swing.JTextField();
        btn_4 = new javax.swing.JButton();
        panel_cadastro = new javax.swing.JTabbedPane();
        panel_identificacao = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        label_cpf = new javax.swing.JLabel();
        label_data_nasc = new javax.swing.JLabel();
        label_numero_civil = new javax.swing.JLabel();
        label_cpf_tutor = new javax.swing.JLabel();
        radio_s_def = new javax.swing.JRadioButton();
        label_status = new javax.swing.JLabel();
        label_sexo = new javax.swing.JLabel();
        label_deficiencia = new javax.swing.JLabel();
        label_sobrenome = new javax.swing.JLabel();
        label_nome_tutor = new javax.swing.JLabel();
        radio_vida_status = new javax.swing.JRadioButton();
        radio_obito_status = new javax.swing.JRadioButton();
        radio_fem = new javax.swing.JRadioButton();
        radio_masc = new javax.swing.JRadioButton();
        radio_n_b = new javax.swing.JRadioButton();
        radio_n_def = new javax.swing.JRadioButton();
        tx_nome = new javax.swing.JTextField();
        tx_cpf = new javax.swing.JTextField();
        txt_sobrenome = new javax.swing.JTextField();
        tx_data = new javax.swing.JFormattedTextField();
        tx_nome_tutor = new javax.swing.JTextField();
        txt_numero_civil = new javax.swing.JTextField();
        tx_cpf_tutor = new javax.swing.JTextField();
        btn_save_identificacao = new javax.swing.JButton();
        panel_pcd = new javax.swing.JPanel();
        label_tipo_de_def = new javax.swing.JLabel();
        cb_def = new javax.swing.JComboBox<>();
        label_nome_def = new javax.swing.JLabel();
        cb_nome_def = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        label_nivel_autonomia = new javax.swing.JLabel();
        radio_nivel_aut = new javax.swing.JRadioButton();
        radio_nivel_pouca = new javax.swing.JRadioButton();
        radio_nivel_nenhuma = new javax.swing.JRadioButton();
        label_laudo_foto = new javax.swing.JLabel();
        panel_laudo_med = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_save_pcd = new javax.swing.JButton();
        panel_endereco = new javax.swing.JPanel();
        label_mun = new javax.swing.JLabel();
        label_bairro = new javax.swing.JLabel();
        label_tipo_residencia = new javax.swing.JLabel();
        label_cep = new javax.swing.JLabel();
        label_rua = new javax.swing.JLabel();
        label_localidade = new javax.swing.JLabel();
        cb_municipio = new javax.swing.JComboBox<>();
        cb_tipo_residencia = new javax.swing.JComboBox<>();
        cb_bairro = new javax.swing.JComboBox<>();
        tx_cep = new javax.swing.JTextField();
        tx_rua = new javax.swing.JTextField();
        radio_urbano = new javax.swing.JRadioButton();
        radio_rural = new javax.swing.JRadioButton();
        label_numero = new javax.swing.JLabel();
        tx_numero_casa = new javax.swing.JTextField();
        btn_save_endereco = new javax.swing.JButton();
        panel_estrutura = new javax.swing.JPanel();
        radio_ativo = new javax.swing.JRadioButton();
        radio_aposentado = new javax.swing.JRadioButton();
        radio_desempregado = new javax.swing.JRadioButton();
        radio_inativo = new javax.swing.JRadioButton();
        radio_dependente = new javax.swing.JRadioButton();
        label_condicoes = new javax.swing.JLabel();
        label_locomocao = new javax.swing.JLabel();
        radio_s_locomoçao = new javax.swing.JRadioButton();
        radio_n_locomoçao = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        radio_s_acessibilidade = new javax.swing.JRadioButton();
        radio_n_acessibilidade = new javax.swing.JRadioButton();
        label_isaude = new javax.swing.JLabel();
        radio_s_isaude = new javax.swing.JRadioButton();
        radio_n_isaude = new javax.swing.JRadioButton();
        cb_escolaridade = new javax.swing.JComboBox<>();
        label_escolaridade = new javax.swing.JLabel();
        btn_save_estrutura = new javax.swing.JButton();
        btn_save_relatorio = new javax.swing.JButton();
        menu_decima = new javax.swing.JPanel();
        label_cadastro_civil = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_delete_relatorio = new javax.swing.JButton();
        menu_lateral = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tela_cadastro_civil = new javax.swing.JLabel();
        label_img_consulta_branco = new javax.swing.JLabel();
        label_sair = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        jMenu15.setText("File");
        jMenuBar3.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar3.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar4.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar4.add(jMenu18);

        jMenuItem4.setText("jMenuItem4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Descreva a situação fisica do civil...");

        tx_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_relatorioActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(76, 175, 79));
        btn_4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("Export relatorio");
        btn_4.setToolTipText("");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        panel_cadastro.setBackground(new java.awt.Color(143, 198, 144));
        panel_cadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panel_cadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_cadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        panel_identificacao.setBackground(new java.awt.Color(217, 217, 217));
        panel_identificacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_nome.setText("Nome : ");

        label_cpf.setText("Cpf:");

        label_data_nasc.setText("Data de nascimento:");

        label_numero_civil.setText("Número de celular:");

        label_cpf_tutor.setText("Cpf tutor e/ou responsável:");

        radio_s_def.setText("Sim");
        radio_s_def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_s_defActionPerformed(evt);
            }
        });

        label_status.setText("Status:");

        label_sexo.setText("Sexo:");

        label_deficiencia.setText("Possui deficiência:");

        label_sobrenome.setText("Sobrenome:");

        label_nome_tutor.setText("Nome tutor e/ou responsável:");

        radio_vida_status.setText("Em vida");
        radio_vida_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_vida_statusActionPerformed(evt);
            }
        });

        radio_obito_status.setText("Em óbito");

        radio_fem.setText("Feminino");

        radio_masc.setText("Masculino");

        radio_n_b.setText("Não binário");

        radio_n_def.setText("Não");

        tx_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nomeActionPerformed(evt);
            }
        });

        tx_data.setText("___/____");
        tx_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_dataActionPerformed(evt);
            }
        });

        tx_nome_tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nome_tutorActionPerformed(evt);
            }
        });

        btn_save_identificacao.setBackground(new java.awt.Color(143, 198, 144));
        btn_save_identificacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_identificacao.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_identificacao.setText("Salvar");

        javax.swing.GroupLayout panel_identificacaoLayout = new javax.swing.GroupLayout(panel_identificacao);
        panel_identificacao.setLayout(panel_identificacaoLayout);
        panel_identificacaoLayout.setHorizontalGroup(
            panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_cpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_numero_civil, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tx_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addComponent(label_nome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tx_data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_cpf, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(label_data_nasc)
                    .addComponent(label_numero_civil))
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nome_tutor)
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_sobrenome)
                                    .addComponent(txt_sobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(label_sexo)
                                    .addComponent(tx_nome_tutor)
                                    .addComponent(tx_cpf_tutor))
                                .addGap(93, 93, 93)
                                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_deficiencia)
                                    .addComponent(label_status)
                                    .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                        .addComponent(radio_vida_status)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_obito_status))))
                            .addComponent(label_cpf_tutor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identificacaoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addComponent(radio_fem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio_masc)
                                .addGap(1, 1, 1)
                                .addComponent(radio_n_b)
                                .addGap(173, 173, 173))
                            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                                .addComponent(radio_s_def)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(radio_n_def)
                        .addGap(220, 220, 220))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identificacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save_identificacao)
                .addGap(35, 35, 35))
        );
        panel_identificacaoLayout.setVerticalGroup(
            panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identificacaoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(label_sobrenome)
                    .addComponent(label_deficiencia))
                .addGap(3, 3, 3)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_sobrenome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radio_s_def)
                        .addComponent(radio_n_def)))
                .addGap(18, 18, 18)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpf)
                    .addComponent(label_sexo)
                    .addComponent(label_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radio_masc)
                        .addComponent(radio_n_b)
                        .addComponent(radio_vida_status)
                        .addComponent(radio_obito_status))
                    .addComponent(radio_fem))
                .addGap(26, 26, 26)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_data_nasc)
                    .addComponent(label_nome_tutor))
                .addGap(5, 5, 5)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_nome_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numero_civil)
                    .addComponent(label_cpf_tutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numero_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_cpf_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btn_save_identificacao)
                .addGap(22, 22, 22))
        );

        panel_cadastro.addTab("Identificação", panel_identificacao);

        panel_pcd.setBackground(new java.awt.Color(217, 217, 217));
        panel_pcd.setToolTipText("");

        label_tipo_de_def.setText("Tipo de deficiência:");

        cb_def.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_nome_def.setText("Nome da deficiência:");

        cb_nome_def.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("A quanto tempo possui?");

        jTextField7.setText("1 ano e 10 meses");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel24.setText("Possui um cuidador?");

        jRadioButton1.setText("Sim");

        jRadioButton7.setText("Não");

        label_nivel_autonomia.setText("Nivel de autonomia:");

        radio_nivel_aut.setText("Autonomia");

        radio_nivel_pouca.setText("Pouca autonomia");

        radio_nivel_nenhuma.setText("Nenhuma autonomia");

        label_laudo_foto.setText("Insira foto do laudo médico:");

        panel_laudo_med.setBackground(new java.awt.Color(0, 102, 0));
        panel_laudo_med.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panel_laudo_medLayout = new javax.swing.GroupLayout(panel_laudo_med);
        panel_laudo_med.setLayout(panel_laudo_medLayout);
        panel_laudo_medLayout.setHorizontalGroup(
            panel_laudo_medLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laudo_medLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );
        panel_laudo_medLayout.setVerticalGroup(
            panel_laudo_medLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_laudo_medLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_save_pcd.setBackground(new java.awt.Color(143, 198, 144));
        btn_save_pcd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_pcd.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_pcd.setText("Salvar");
        btn_save_pcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_pcdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_pcdLayout = new javax.swing.GroupLayout(panel_pcd);
        panel_pcd.setLayout(panel_pcdLayout);
        panel_pcdLayout.setHorizontalGroup(
            panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pcdLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addComponent(radio_nivel_aut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_nivel_pouca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_nivel_nenhuma))
                    .addComponent(label_nivel_autonomia)
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_nome_def)
                            .addComponent(label_tipo_de_def)
                            .addComponent(cb_nome_def, 0, 172, Short.MAX_VALUE)
                            .addComponent(cb_def, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pcdLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7))
                            .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_pcdLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(117, 117, 117)
                                    .addComponent(label_laudo_foto))
                                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pcdLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(285, 285, 285))
                                    .addGroup(panel_pcdLayout.createSequentialGroup()
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panel_laudo_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pcdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save_pcd)
                .addGap(34, 34, 34))
        );
        panel_pcdLayout.setVerticalGroup(
            panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pcdLayout.createSequentialGroup()
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcdLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(label_tipo_de_def))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pcdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_laudo_foto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(4, 4, 4)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_laudo_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome_def)
                    .addComponent(jLabel24))
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_nome_def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton7)))
                .addGap(35, 35, 35)
                .addComponent(label_nivel_autonomia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pcdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_nivel_aut)
                    .addComponent(radio_nivel_pouca)
                    .addComponent(radio_nivel_nenhuma))
                .addGap(137, 137, 137)
                .addComponent(btn_save_pcd)
                .addGap(20, 20, 20))
        );

        panel_cadastro.addTab("PCD", panel_pcd);

        panel_endereco.setBackground(new java.awt.Color(217, 217, 217));

        label_mun.setText("Municipio:");

        label_bairro.setText("Bairro:");

        label_tipo_residencia.setText("Tipo de residência:");

        label_cep.setText("Cep:");

        label_rua.setText("Rua:");

        label_localidade.setText("Localidade:");

        cb_municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "municipio 1", "municipio 2", "municipio 3", "Item 4" }));

        cb_tipo_residencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo 1", "tipo 2", "tipo 3", "Item 4" }));

        cb_bairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bairro 1", "bairro 2", "bairro 3", "bairro 4" }));

        tx_cep.setText("00000000");

        tx_rua.setText("rua nome");

        radio_urbano.setText("Urbana");

        radio_rural.setText("Rural");

        label_numero.setText("Número:");

        tx_numero_casa.setText("numero");

        btn_save_endereco.setBackground(new java.awt.Color(143, 198, 144));
        btn_save_endereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_endereco.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_endereco.setText("Salvar");
        btn_save_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_enderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_enderecoLayout = new javax.swing.GroupLayout(panel_endereco);
        panel_endereco.setLayout(panel_enderecoLayout);
        panel_enderecoLayout.setHorizontalGroup(
            panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_enderecoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_numero)
                    .addGroup(panel_enderecoLayout.createSequentialGroup()
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_mun)
                            .addComponent(label_bairro)
                            .addComponent(cb_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cep)
                            .addComponent(label_rua)
                            .addComponent(tx_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_tipo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_tipo_residencia)
                            .addComponent(label_localidade)
                            .addGroup(panel_enderecoLayout.createSequentialGroup()
                                .addComponent(radio_urbano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio_rural))))
                    .addComponent(tx_numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_enderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save_endereco)
                .addGap(36, 36, 36))
        );
        panel_enderecoLayout.setVerticalGroup(
            panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_enderecoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_mun)
                    .addComponent(label_cep)
                    .addComponent(label_localidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_urbano)
                    .addComponent(radio_rural))
                .addGap(41, 41, 41)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_bairro)
                    .addComponent(label_rua)
                    .addComponent(label_tipo_residencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tipo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(label_numero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btn_save_endereco)
                .addGap(20, 20, 20))
        );

        panel_cadastro.addTab("Endereço", panel_endereco);

        panel_estrutura.setBackground(new java.awt.Color(217, 217, 217));

        radio_ativo.setText("Ativo");

        radio_aposentado.setText("Aposentado");

        radio_desempregado.setText("Desempregado");

        radio_inativo.setText("Inativo");

        radio_dependente.setText("Dependente");

        label_condicoes.setText("Condições socieconômicas:");

        label_locomocao.setText("Dificuldade de locomoção dentro do municipio?");

        radio_s_locomoçao.setText("Sim");

        radio_n_locomoçao.setText("Não");

        jLabel27.setText("Encontra acessibilidade no acesso local?");

        radio_s_acessibilidade.setText("Sim");

        radio_n_acessibilidade.setText("Não");

        label_isaude.setText("Possui facil acesso a instituições de saúde?");

        radio_s_isaude.setText("Sim");

        radio_n_isaude.setText("Não");

        cb_escolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "opcao 1", "opcao 2", "opcao 3", "opcao 4" }));

        label_escolaridade.setText("Nivel de escolaridade?");

        btn_save_estrutura.setBackground(new java.awt.Color(143, 198, 144));
        btn_save_estrutura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_estrutura.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_estrutura.setText("Cadastrar civil");
        btn_save_estrutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_estruturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_estruturaLayout = new javax.swing.GroupLayout(panel_estrutura);
        panel_estrutura.setLayout(panel_estruturaLayout);
        panel_estruturaLayout.setHorizontalGroup(
            panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estruturaLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_condicoes)
                    .addComponent(radio_ativo)
                    .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radio_desempregado)
                        .addComponent(radio_aposentado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radio_inativo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radio_dependente, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(label_locomocao)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_locomoçao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_locomoçao)))
                .addGap(144, 144, 144)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_isaude)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_acessibilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_acessibilidade))
                    .addComponent(jLabel27)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_s_isaude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_n_isaude))
                    .addComponent(label_escolaridade))
                .addContainerGap(446, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_estruturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save_estrutura)
                .addGap(34, 34, 34))
        );
        panel_estruturaLayout.setVerticalGroup(
            panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estruturaLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_condicoes)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_ativo)
                    .addComponent(radio_s_acessibilidade)
                    .addComponent(radio_n_acessibilidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_aposentado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_desempregado)
                    .addComponent(label_isaude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_inativo)
                    .addComponent(radio_s_isaude)
                    .addComponent(radio_n_isaude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_estruturaLayout.createSequentialGroup()
                        .addComponent(radio_dependente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_locomocao, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_escolaridade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_estruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_s_locomoçao)
                    .addComponent(radio_n_locomoçao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btn_save_estrutura)
                .addGap(21, 21, 21))
        );

        panel_cadastro.addTab("Estrutura", panel_estrutura);

        btn_save_relatorio.setBackground(new java.awt.Color(76, 175, 79));
        btn_save_relatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_save_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_relatorio.setText("Salvar relatorio");
        btn_save_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_relatorioActionPerformed(evt);
            }
        });

        menu_decima.setBackground(new java.awt.Color(255, 255, 255));
        menu_decima.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_decima.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menu_decimaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        label_cadastro_civil.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label_cadastro_civil.setText("Cadastro de civil");
        label_cadastro_civil.setMaximumSize(new java.awt.Dimension(200, 47));
        label_cadastro_civil.setMinimumSize(new java.awt.Dimension(100, 16));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Olá, Fulano Silva!");

        javax.swing.GroupLayout menu_decimaLayout = new javax.swing.GroupLayout(menu_decima);
        menu_decima.setLayout(menu_decimaLayout);
        menu_decimaLayout.setHorizontalGroup(
            menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_decimaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(label_cadastro_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(34, 34, 34))
        );
        menu_decimaLayout.setVerticalGroup(
            menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_decimaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menu_decimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_cadastro_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel5)
                        .addGroup(menu_decimaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_delete_relatorio.setBackground(new java.awt.Color(212, 0, 0));
        btn_delete_relatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_relatorio.setText("Excluir relatorio");

        menu_lateral.setBackground(new java.awt.Color(30, 101, 40));

        tela_cadastro_civil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tela_cadastro_civilMouseClicked(evt);
            }
        });

        label_img_consulta_branco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_img_consulta_brancoMouseClicked(evt);
            }
        });

        label_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_sairMouseClicked(evt);
            }
        });

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menu_lateralLayout = new javax.swing.GroupLayout(menu_lateral);
        menu_lateral.setLayout(menu_lateralLayout);
        menu_lateralLayout.setHorizontalGroup(
            menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_lateralLayout.createSequentialGroup()
                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(menu_lateralLayout.createSequentialGroup()
                                    .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addGap(67, 67, 67))
                                .addGroup(menu_lateralLayout.createSequentialGroup()
                                    .addComponent(label_sair)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20))))
                            .addComponent(jLabel17)
                            .addGroup(menu_lateralLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel18)
                                    .addComponent(label_img_consulta_branco)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))))
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tela_cadastro_civil))
                    .addGroup(menu_lateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_lateralLayout.setVerticalGroup(
            menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_lateralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tela_cadastro_civil)
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGap(60, 60, 60)
                .addComponent(label_img_consulta_branco)
                .addGap(69, 69, 69)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(72, 72, 72)
                .addComponent(jLabel9)
                .addGap(69, 69, 69)
                .addComponent(label_sair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(107, 107, 107)
                .addComponent(jLabel20)
                .addGap(124, 124, 124))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lahra souza nunes", "gustavo santana", "matheus soares" }));

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(menu_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_decima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btn_2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(btn_save_relatorio)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete_relatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btn_4))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_relatorio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_cadastro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(111, 111, Short.MAX_VALUE))))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_2Layout.createSequentialGroup()
                        .addComponent(menu_decima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panel_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_4)
                            .addComponent(btn_save_relatorio)
                            .addComponent(btn_delete_relatorio)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(menu_lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_relatorioActionPerformed

        tela_cadastro_civil.this.dispose();
        tela_consulta_daddos objeto1 = new tela_consulta_daddos();
        objeto1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_relatorioActionPerformed

    private void tx_nome_tutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nome_tutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nome_tutorActionPerformed

    private void tx_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_dataActionPerformed

    private void tx_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nomeActionPerformed

    private void radio_s_defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_s_defActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_s_defActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed

        try {
           String desktopPath = System.getProperty("user.home") + "/Desktop/";
            File desktopDir = new File(desktopPath);
            if (!desktopDir.exists()) {
                desktopDir.mkdirs(); // Cria o diretório se não existir
            }
            String filePath = desktopPath + "RELATORIO.txt";
            FileWriter arquivo = new FileWriter(filePath);
            PrintWriter escrever = new PrintWriter(arquivo);

            escrever.printf("Relatorio descritivo sobre civil: " + tx_relatorio.getText());

            arquivo.close();

            JOptionPane.showMessageDialog(null, "Arquivo exportado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(tela_cadastro_civil.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao exportar o arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void tx_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_relatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_relatorioActionPerformed

    private void panel_cadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_cadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_cadastroAncestorAdded

    private void menu_decimaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menu_decimaAncestorAdded



        // TODO add your handling code here:
    }//GEN-LAST:event_menu_decimaAncestorAdded

    private void radio_vida_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_vida_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_vida_statusActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btn_save_pcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_pcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_pcdActionPerformed

    private void btn_save_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_enderecoActionPerformed

    private void tela_cadastro_civilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tela_cadastro_civilMouseClicked

         tela_cadastro_civil.this.dispose();
        tela_cadastro_civil objeto = new tela_cadastro_civil();
        objeto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tela_cadastro_civilMouseClicked

    private void label_img_consulta_brancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_img_consulta_brancoMouseClicked

        tela_cadastro_civil.this.dispose();
        tela_consulta_daddos objeto = new tela_consulta_daddos();
        objeto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_label_img_consulta_brancoMouseClicked

    private void label_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sairMouseClicked

        JOptionPane.showMessageDialog(null, "Você saiu do sistema!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_label_sairMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        tela_cadastro_civil.this.dispose();
        tela_dashbord objeto2 = new tela_dashbord();
        objeto2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_save_estruturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_estruturaActionPerformed
       tela_cadastro_civil.this.dispose();
        tela_consulta_daddos objeto2 = new  tela_consulta_daddos();
        objeto2.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_estruturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro_civil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_2;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_delete_relatorio;
    private javax.swing.JButton btn_save_endereco;
    private javax.swing.JButton btn_save_estrutura;
    private javax.swing.JButton btn_save_identificacao;
    private javax.swing.JButton btn_save_pcd;
    private javax.swing.JButton btn_save_relatorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cb_bairro;
    private javax.swing.JComboBox<String> cb_def;
    private javax.swing.JComboBox<String> cb_escolaridade;
    private javax.swing.JComboBox<String> cb_municipio;
    private javax.swing.JComboBox<String> cb_nome_def;
    private javax.swing.JComboBox<String> cb_tipo_residencia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel label_bairro;
    private javax.swing.JLabel label_cadastro_civil;
    private javax.swing.JLabel label_cep;
    private javax.swing.JLabel label_condicoes;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_cpf_tutor;
    private javax.swing.JLabel label_data_nasc;
    private javax.swing.JLabel label_deficiencia;
    private javax.swing.JLabel label_escolaridade;
    private javax.swing.JLabel label_img_consulta_branco;
    private javax.swing.JLabel label_isaude;
    private javax.swing.JLabel label_laudo_foto;
    private javax.swing.JLabel label_localidade;
    private javax.swing.JLabel label_locomocao;
    private javax.swing.JLabel label_mun;
    private javax.swing.JLabel label_nivel_autonomia;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_nome_def;
    private javax.swing.JLabel label_nome_tutor;
    private javax.swing.JLabel label_numero;
    private javax.swing.JLabel label_numero_civil;
    private javax.swing.JLabel label_rua;
    private javax.swing.JLabel label_sair;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel label_sobrenome;
    private javax.swing.JLabel label_status;
    private javax.swing.JLabel label_tipo_de_def;
    private javax.swing.JLabel label_tipo_residencia;
    private javax.swing.JPanel menu_decima;
    private javax.swing.JPanel menu_lateral;
    private javax.swing.JTabbedPane panel_cadastro;
    private javax.swing.JPanel panel_endereco;
    private javax.swing.JPanel panel_estrutura;
    private javax.swing.JPanel panel_identificacao;
    private javax.swing.JPanel panel_laudo_med;
    private javax.swing.JPanel panel_pcd;
    private javax.swing.JRadioButton radio_aposentado;
    private javax.swing.JRadioButton radio_ativo;
    private javax.swing.JRadioButton radio_dependente;
    private javax.swing.JRadioButton radio_desempregado;
    private javax.swing.JRadioButton radio_fem;
    private javax.swing.JRadioButton radio_inativo;
    private javax.swing.JRadioButton radio_masc;
    private javax.swing.JRadioButton radio_n_acessibilidade;
    private javax.swing.JRadioButton radio_n_b;
    private javax.swing.JRadioButton radio_n_def;
    private javax.swing.JRadioButton radio_n_isaude;
    private javax.swing.JRadioButton radio_n_locomoçao;
    private javax.swing.JRadioButton radio_nivel_aut;
    private javax.swing.JRadioButton radio_nivel_nenhuma;
    private javax.swing.JRadioButton radio_nivel_pouca;
    private javax.swing.JRadioButton radio_obito_status;
    private javax.swing.JRadioButton radio_rural;
    private javax.swing.JRadioButton radio_s_acessibilidade;
    private javax.swing.JRadioButton radio_s_def;
    private javax.swing.JRadioButton radio_s_isaude;
    private javax.swing.JRadioButton radio_s_locomoçao;
    private javax.swing.JRadioButton radio_urbano;
    private javax.swing.JRadioButton radio_vida_status;
    private javax.swing.JLabel tela_cadastro_civil;
    private javax.swing.JTextField tx_cep;
    private javax.swing.JTextField tx_cpf;
    private javax.swing.JTextField tx_cpf_tutor;
    private javax.swing.JFormattedTextField tx_data;
    private javax.swing.JTextField tx_nome;
    private javax.swing.JTextField tx_nome_tutor;
    private javax.swing.JTextField tx_numero_casa;
    private javax.swing.JTextField tx_relatorio;
    private javax.swing.JTextField tx_rua;
    private javax.swing.JTextField txt_numero_civil;
    private javax.swing.JTextField txt_sobrenome;
    // End of variables declaration//GEN-END:variables
}
